local MODULES = {
    { name = "src.binary", path = "src/binary.lua" },
    { name = "src.checksum", path = "src/checksum.lua" },
    { name = "src.zlib", path = "src/zlib.lua" },
    { name = "src.png", path = "src/png.lua" },
    { name = "src.rttex", path = "src/rttex.lua" },
    { name = "src.items_dat", path = "src/items_dat.lua" },
    { name = "src.world_dat", path = "src/world_dat.lua" },
    { name = "src.inspect", path = "src/inspect.lua" },
    { name = "src.cli", path = "src/cli.lua" },
}

local OUTPUT_PATH = "dist/rttex_tools.lua"

local function read_file(path)
    local file = assert(io.open(path, "rb"))
    local data = file:read("a")
    file:close()
    return data
end

local function write_file(path, data)
    local file = assert(io.open(path, "wb"))
    file:write(data)
    file:close()
end

local function make_directory(path)
    local ok = os.execute("mkdir -p " .. path)
    if ok ~= true and ok ~= 0 then
        error("Failed to create directory: " .. path)
    end
end

local function module_chunk(module)
    return "package.preload[" .. string.format("%q", module.name) .. "] = function(...)\n"
        .. read_file(module.path)
        .. "\nend\n\n"
end

local function build_bundle()
    local output = {
        "-- Generated by tools/bundle.lua. Do not edit manually.\n",
        "-- GrowToolsLua: pure Lua 5.4 RTTEX and items.dat tools.\n\n",
    }

    for _, module in ipairs(MODULES) do
        output[#output + 1] = module_chunk(module)
    end

    output[#output + 1] = [[
local Rttex = require("src.rttex")

if type(arg) == "table" and type(arg[0]) == "string" and arg[0]:match("rttex_tools%.lua$") then
    require("src.cli").run(arg)
end

return Rttex
]]

    return table.concat(output)
end

make_directory("dist")
write_file(OUTPUT_PATH, build_bundle())
print("Wrote " .. OUTPUT_PATH)
