local MODULES = {
    { public_name = "GTLua.binary", internal_name = "src.binary", path = "src/binary.lua" },
    { public_name = "GTLua.checksum", internal_name = "src.checksum", path = "src/checksum.lua" },
    { public_name = "GTLua.zlib", internal_name = "src.zlib", path = "src/zlib.lua" },
    { public_name = "GTLua.png", internal_name = "src.png", path = "src/png.lua" },
    { public_name = "GTLua.rttex", internal_name = "src.rttex", path = "src/rttex.lua" },
    { public_name = "GTLua.items_dat", internal_name = "src.items_dat", path = "src/items_dat.lua" },
    { public_name = "GTLua.cbor", internal_name = "src.cbor", path = "src/cbor.lua" },
    { public_name = "GTLua.world_dat", internal_name = "src.world_dat", path = "src/world_dat.lua" },
    { public_name = "GTLua.inspect", internal_name = "src.inspect", path = "src/inspect.lua" },
    { public_name = "GTLua.cli", internal_name = "src.cli", path = "src/cli.lua" },
}

local OUTPUT_PATH = "dist/GrowToolsLua.lua"

local function read_file(path)
    local file = assert(io.open(path, "rb"))
    local data = file:read("a")
    file:close()
    return data
end

local function write_file(path, data)
    local file = assert(io.open(path, "wb"))
    file:write(data)
    file:close()
end

local function make_directory(path)
    local ok = os.execute("mkdir -p " .. path)
    if ok ~= true and ok ~= 0 then
        error("Failed to create directory: " .. path)
    end
end

local function module_chunk(module)
    return "package.preload[" .. string.format("%q", module.public_name) .. "] = function(...)\n"
        .. read_file(module.path)
        .. "\nend\n"
        .. "package.preload[" .. string.format("%q", module.internal_name) .. "] = package.preload[" .. string.format("%q", module.public_name) .. "]\n\n"
end

local function build_bundle()
    local output = {
        "-- Generated by tools/bundle.lua. Do not edit manually.\n",
        "-- GrowToolsLua: pure Lua 5.4 Growtopia asset tools.\n\n",
    }

    for _, module in ipairs(MODULES) do
        output[#output + 1] = module_chunk(module)
    end

    output[#output + 1] = [[
local GTLua = {
    binary = require("GTLua.binary"),
    checksum = require("GTLua.checksum"),
    zlib = require("GTLua.zlib"),
    png = require("GTLua.png"),
    rttex = require("GTLua.rttex"),
    items_dat = require("GTLua.items_dat"),
    cbor = require("GTLua.cbor"),
    world_dat = require("GTLua.world_dat"),
}

GTLua.RTTEXPack = GTLua.rttex.RTTEXPack
GTLua.RTTEXUnpack = GTLua.rttex.RTTEXUnpack

if type(arg) == "table" and type(arg[0]) == "string" and arg[0]:match("rttex_tools%.lua$") then
    require("GTLua.cli").run(arg)
elseif type(arg) == "table" and type(arg[0]) == "string" and arg[0]:match("GrowToolsLua%.lua$") then
    require("GTLua.cli").run(arg)
end

return GTLua
]]

    return table.concat(output)
end

make_directory("dist")
write_file(OUTPUT_PATH, build_bundle())
print("Wrote " .. OUTPUT_PATH)
